### ISSUE TITLE
ImportError: No module named vanilla

### ISSUE THREAD

**Issue by tomtompy** [huertatipografica/HTLetterspacer#22]
Hi,

I have this message in the console 👍 
`ImportError: No module named vanilla`

What's wrong ? 
Mac OS up to date, last Glyphs

**Comment by m4rc1e** [comment]
Have you installed addons?

![screen shot 2016-09-15 at 12 30 46](https://cloud.githubusercontent.com/assets/7525512/18546815/4a10f110-7b40-11e6-9f70-b052c2b575be.png)

**Comment by anthrotype** [comment]
@m4rc1e I didn't know that! I wonder where it installs the packages. It's asking for the administrator's password, so I guess it attempts to install to the system's site-packages, which is not a good thing to do, IMHO.

@schriftgestalt maybe you could install somewhere to `~/Library/Application Support/Glyphs/` and then extend the `sys.path` at runtime to include the path containing those addons?

**Comment by tomtompy** [comment]
Thank you M4rc1e / No more error but no panel… I try an OS reboot.

**Comment by tomtompy** [comment]
I reboot, no « Auto espaciar » windows. Is it a shortcut ?

**Comment by m4rc1e** [comment]
Could you run the script then paste the error message for us?

Error message should come up in the macro window

**Comment by tomtompy** [comment]
No error in macro window… I can launch the script but the window looks usefull.
`Start









\five\
\eight\
\six\
\one\
\nine\
\three\
\seven\
\two\
\four\
Using master custom parameter, paramArea: 500.0
Using master custom parameter, paramDepth: 17.0
Using master custom parameter, paramOver: 3.0

End`
