### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by synthview** [huertatipografica/HTLetterspacer#23]
Hello,
I can see the UI but pressing “apply” gives this message into macro (and nothing else happens)

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "HT_LetterSpacer.py", line 131, in dialogCallback
    self.engine.width = float(self.w.width.get())
ValueError: could not convert string to float:

**Comment by andrestelex** [comment]
Please be sure you are entering a valid integrer value inside Tabular width field or a positive integrer number, which is not being converted to a number value.
If I enter 0 as a value and mark the Tabular checkbox I have the same error.
