### ISSUE TITLE
Docs: maybe include an "Installation" section?

### ISSUE THREAD

**Issue by jpt** [huertatipografica/HTLetterspacer#24]
It may not be clear to those newer to the Glyphs ecosystem on how to install. Maybe tell them how to open the Scripts folder, to make sure objectGS is there, install robofab, etc. Worthwhile? I'm happy to help on this with a PR.

Or is this getting packaged up as a plugin so this won't be necessary soon?

**Comment by davelab6** [comment]
@jpt would be great if you can make a PR for the README/INSTALL file :)
