### ISSUE TITLE
UI blocks selection

### ISSUE THREAD

**Issue by impallari** [huertatipografica/HTLetterspacer#26]
Using the UI blocks the selection of new glyphs

How to reproduce the problem:
Select some glyphs (ie "abcd") and open the script using "window=true"
Click OK and "abcd" will be spaced, as expected.
But now, if you select other glyphs (ie "efghijk") when you click OK this new selection will be ignored, and the initial selection "abcd" will be spaced instead.

**Comment by simoncozens** [comment]
This could be fixed by adding before line 132:

```
		self.mySelection = list(set(Glyphs.font.selectedLayers))
```

But I wonder if there was a reason why it captures `mySelection` in the initialization stage, not at the point of use?

**Comment by andrestelex** [comment]
I added Simon's proposal.
There is no special reason, I brought this way of doing it from the begining where I didn't think about changing the glyph selection after running the script.
I don't know if will be hard to change this and if it will be worth.
