### ISSUE TITLE
Update preview after spacing

### ISSUE THREAD

**Issue by impallari** [huertatipografica/HTLetterspacer#27]
I suggest adding this line somewhere, so the preview is updated on the fly
Glyphs.currentDocument.windowController().activeEditViewController().updatePreview()

**Comment by andrestelex** [comment]
Fixed adding this line inside `spaceMain` function. It's not the same. Your proposal only updated preview panel, `forceRedraw` also updates the current tab view. :)

`Glyphs.currentDocument.windowController().activeEditViewController().forceRedraw()`

**Comment by schriftgestalt** [comment]
That line should be `Glyphs.font.currentTab.forceRedraw()`

**Comment by andrestelex** [comment]
Thanks Georg!

**Comment by alexeiva** [comment]
I am getting this traceback error in `2.4RC (934)` if I run the script while the font view tab with all glyphs is active. No error if run from preview tabs. In all case the script does it's job.
<img width="739" alt="screen shot 2016-11-04 at 19 03 16" src="https://cloud.githubusercontent.com/assets/16634089/20025077/6cbd6042-a2c1-11e6-8f28-bab32d4ee83e.png">

```
Traceback (most recent call last):
  File "HT_LetterSpacer.py", line 230, in <module>
    HTLetterspacerScript()
  File "HT_LetterSpacer.py", line 85, in __init__
    self.spaceMain()
  File "HT_LetterSpacer.py", line 225, in spaceMain
    self.font.currentTab.forceRedraw()
AttributeError: 'NoneType' object has no attribute 'forceRedraw'
```

**Comment by andrestelex** [comment]
Thanks Alexei. ForceRedraw seems to work only with tab, there should be a condition there. I will do it as soon as I can, but in the meanwhile if you need to use it in this way you can comment line 225 to avoid the error.

**Comment by andrestelex** [comment]
Fixed.
