### ISSUE TITLE
Not working on a particular font

### ISSUE THREAD

**Issue by kemie** [huertatipografica/HTLetterspacer#44]
Suddenly can't get HTLS to work on a particular font. Let me explain: whether I have the settings in parameters or through the UI the result is the same: the paramArea setting is completely ignored, and I get negative sidebearings on every single glyph, corresponding to the depth parameter. In other fonts the script is working as should. What could be different about this one?

![Alt text](https://monosnap.com/image/sFlPnJBxkkHewyLMSiCnrjPOP1S1Lx.png)

**Comment by kemie** [comment]
Answering myself: after lots of trial and error I found out the apparent cause: I had the UPM for the font set at 925. Setting it to 1000 made the script work as expected again.

**Comment by davelab6** [comment]
Thanks for figuring this out! I guess to close this issue, there's a long and short term fix... 

Short term, the script should check the UPM and error/halt if it is not 1000. 

Long time, the script should multiply its results to work with any UPM.
