### ISSUE TITLE
Something is wrong in `diagonize`

### ISSUE THREAD

**Issue by simoncozens** [huertatipografica/HTLetterspacer#45]
(See also #8)

Normally `diagonize` uses the difference in Y values to check if a point has an angle of greater than 45 degrees (i.e. if x diff > y diff). That I can understand.

But when it is going backwards down the *left* margin (and not the right margin) it uses `valueFreq`. I don't think this can be right:
https://github.com/huertatipografica/HTLetterspacer/blob/92b2593409f1123c1b03884d5fa18f2bd0cfd0b8/HT_LetterSpacer_script.py#L255

There's another commented out line which uses `valueFreq`:

https://github.com/huertatipografica/HTLetterspacer/blob/92b2593409f1123c1b03884d5fa18f2bd0cfd0b8/HT_LetterSpacer_script.py#L247

The commenting-out suggests to me that whoever edited this last wasn't quite sure what it was supposed to do. I think `diff` is correct and `valueFreq` is wrong, but I am not confident enough to rewrite to function.

**Comment by simoncozens** [comment]
Also: I am pretty sure that `marginsL` and `marginsR` are guaranteed to be in y-ascending order. The test `and nextPoint.y > actualPoint.y` seems redundant. Is it?

**Comment by simoncozens** [comment]
Here's a refactoring:

```Python
	# close counters at 45 degrees
	def diagonize(self, marginsL, marginsR):
		for actualPoint, nextPoint in pairwise(marginsL):
			ydiff = nextPoint.y - actualPoint.y
			nextPoint.x = min(nextPoint.x, actualPoint.x + ydiff)

		for actualPoint, nextPoint in pairwise(marginsR):
			ydiff = nextPoint.y - actualPoint.y
			nextPoint.x = max(actualPoint.x - ydiff, nextPoint.x)

		for actualPoint, nextPoint in pairwise(reversed(marginsL)):
			diff=actualPoint.y - nextPoint.y
			nextPoint.x = min(nextPoint.x, actualPoint.x + diff)

		for actualPoint, nextPoint in pairwise(reversed(marginsR)):
			diff=actualPoint.y - nextPoint.y
			nextPoint.x = max(actualPoint.x - diff, nextPoint.x)

		return marginsL, marginsR
```

Requires `pairwise` from itertools:

```Python
from itertools import tee, izip

def pairwise(iterable):
  a, b = tee(iterable)
  next(b, None)
  return izip(a, b)
```

**Comment by simoncozens** [comment]
And here's another. Choose whichever you prefer!

```Python
	def diagonize(self, marginsL, marginsR):
		ystep = abs(marginsL[0].y - marginsL[1].y)
		for i in range(len(marginsL)-1):
			if marginsL[i+1].x - marginsL[i].x > ystep: marginsL[i+1].x = marginsL[i].x + ystep
			if marginsR[i+1].x - marginsR[i].x < -ystep: marginsR[i+1].x = marginsR[i].x - ystep

		for i in reversed(range(len(marginsL)-1)):
			if marginsL[i].x - marginsL[i+1].x > ystep: marginsL[i].x = marginsL[i+1].x + ystep
			if marginsR[i].x - marginsR[i+1].x < -ystep: marginsR[i].x = marginsR[i+1].x - ystep

		return marginsL, marginsR
```

**Comment by andrestelex** [comment]
Thanks for this. I'll update soon.
I've never came up with a more advanced solution, that allows us to use a custom angle. This method is sort of grid-fitted and only allows to diagonize at 45 degrees.

**Comment by madig** [comment]
For what it's worth, neither code snippet is a drop-in replacement. My unit test of Merriweather Light Italic fails.

**Comment by simoncozens** [comment]
I believe the use of valueFreq was wrong, so this is a bug fix. I would expect changes.

**Comment by madig** [comment]
So!!!!!!!!!!!!!!!!!!

Merriweather Light Italic, old algorithm, you're seeing the deslanted glyph with the left and  right polygons `diagonize` produces, original outline faintly in the background:

![grafik](https://user-images.githubusercontent.com/380829/105106026-329e2880-5aad-11eb-92dc-cb01a6ae23c1.png)

Algorithm from https://github.com/huertatipografica/HTLetterspacer/issues/45#issuecomment-457586668:

![grafik](https://user-images.githubusercontent.com/380829/105106073-49447f80-5aad-11eb-82d5-4704f2cce624.png)

Who's righter? You see that it does lead to a spacing diff.
