### ISSUE TITLE
A visual explanation

### ISSUE THREAD

**Issue by simoncozens** [huertatipografica/HTLetterspacer#46]
For my own use, I made this image explaining how HTLetterspacer works:
![explanation](https://user-images.githubusercontent.com/106728/51793521-92f97880-21b9-11e9-8e42-4e0c0be47964.png)

It's aimed more at people playing with the code as it mentions the different variables and routines, but it also functions as a conceptual overview. Feel free to use it. I can provide Illustrator files if wanted.

**Comment by davelab6** [comment]
Nice! I suggest to submit a PR with illustrator sources in svg format + png

**Comment by andrestelex** [comment]
Great stuff! Thanks for that! I can add this pic and an SVG file to the repo.
