### ISSUE TITLE
Deitalicizing side-bearing values for italic fonts?

### ISSUE THREAD

**Issue by madig** [huertatipografica/HTLetterspacer#56]
I'm looking at breaking up the code and making a neat copy of the core algorithm, to make it work on UFOs and provide a better base for editor-specific scripts. I'm running into trouble with italic fonts; the final side-bearings produced by the algorithm seem to be made specifically for Glyphs.app's automatic value conversion when dealing with italic fonts. 

From what I can glean, Glyphs.app (and optionally FontLab 7) measures italic side-bearings from `y = xHeight / 2` with a measurement line following the italic angle instead of `y = 0` and a straight-up line like in non-italic fonts.

![grafik](https://user-images.githubusercontent.com/380829/103468298-8be92680-4d4f-11eb-973f-24844d3a5861.png)

The `-11` and `10` values are what come out of HT Letterspacer. There is no such standardized italic side-bearings measuring in the UFO world, so I need to de-italicize these values to arrive at:

![grafik](https://user-images.githubusercontent.com/380829/103468288-75db6600-4d4f-11eb-9202-bcef77c00e55.png)

I think there are two options here:

1. Deitalicize the final values
2. Stop HT Letterspacer from italicizing the values in the first place

So far, I have failed at both. The former because I can't find a calculation that spits out what Glyphs.app does and the latter because taking out all the `(slant|deSlant)` calls from the code doesn't actually do much because the side-bearing computation seems to be independent of the angle anyway?!

Halp!

**Comment by schriftgestalt** [comment]
Glyphs is generating a NSBezierPath from the layer and then back-slants it on the half x-height. Then measures the bounding box of that NSBezierpath.

**Comment by madig** [comment]
"Generates a NSBezierPath" as in it applies a negative angle skew transformation with origin = xheight / 2? And how does it take an italic side-bearing like `11` and transform it into `-62`?

**Comment by schriftgestalt** [comment]
It doesn't deal with the none slanted sidebearing at all. All operations work on the UI value.

**Comment by madig** [comment]
Ok thanks. Figured it out. Code follows once I am ready for a PR.
