### ISSUE TITLE
Error: local variable 'lefty' referenced before assignment

### ISSUE THREAD

**Issue by mekkablue** [huertatipografica/HTLetterspacer#59]
When running HT Letterspacer on Glyphs 3, users are confronted with this error frequently:

```python
Traceback (most recent call last):
  File "HT_LetterSpacer_script.py", line 400, in spaceMain
  File "HT_LetterSpacer_script.py", line 342, in setSpace
  File "HT_LetterSpacer_script.py", line 196, in maxPoints
UnboundLocalError: local variable 'lefty' referenced before assignment

\n\
```

Looking at the function in question, the variables `lefty` and `righty` have no fallback values:

```python
	def maxPoints(self, points, minY, maxY):
		right = -10000
		left = 10000
		for p in points:
			if p.y >= minY and p.y <= maxY:
				if p.x > right:
					right = p.x
					righty = p.y
				if p.x < left:
					left = p.x
					lefty = p.y
		return NSMakePoint(left, lefty), NSMakePoint(right, righty)
```

Consider changing the variable definitions to something like:

```python
		right, righty = -10000, 0
		left, lefty = 10000, 0
```

**Comment by uberfont** [comment]
What can I do know ? I have this message, I don't have the competence for resolving this problem :

Traceback (most recent call last):
  File "HT_LetterSpacer_script.py", line 400, in spaceMain
  File "HT_LetterSpacer_script.py", line 349, in setSpace
  File "HT_LetterSpacer_script.py", line 310, in calculateSBValue
AttributeError: 'HTLetterspacerLib' object has no attribute 'factor'

\A\

**Comment by madig** [comment]
I was wondering what the default values for `lefty` and `righty` should be. If it can't be assigned, something seems wrong anyway? Are there any open fonts where this problem can be demonstrated?

**Comment by madig** [comment]
@mekkablue @uberfont please test with master. Maybe I fixed this.

**Comment by andrestelex** [comment]
> What can I do know ? I have this message, I don't have the skill for resolving this problem :
> 
> ```
> Traceback (most recent call last):
>   File "HT_LetterSpacer_script.py", line 400, in spaceMain
>   File "HT_LetterSpacer_script.py", line 349, in setSpace
>   File "HT_LetterSpacer_script.py", line 310, in calculateSBValue
> AttributeError: 'HTLetterspacerLib' object has no attribute 'factor'
> 
> \A\
> ```

@uberfont I suspect your problem is because the glyph doesn't match any category in the config file. Can you check that file is ok? Can you report the glyph and send the file so I can review it? Thanks

**Comment by andrestelex** [comment]
I did an update to skip a glyph if the bounding box doesn't overlap with the reference (for example, a sign below the baseline when the reference is x). About mxPoints I left a note explaining what the function does in a very unnefficient way

**Comment by madig** [comment]
The code should now default to a factor of 1 if nothing is found in the config file.

**Comment by uberfont** [comment]
Congratulations, it's worked !

**Comment by sebsan** [comment]
Hi, I can't get it to work. It does some bizarre stuff like giving negative values to all side bearings. Changing the Area and Depth parameters doesn't actually impact the results. If I add a value to the Overshoot parameter the Glyphs app crashes. The marco panel doesn't seem to give me an error message, as far as I understand. This is what I get if I select the lette r, for exemple.
`Config file exists
0.0

\r\`
